### ISSUE TITLE
supervisord.conf username issue

### ISSUE THREAD

**Issue by sifnoc** [datascienceschool/docker_rpython#1]
[program:notebook]
**user=dockeruser**
command=jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
startsecs=0
autorestart=false

supervisord.conf 파일의 username과 Dockerfile 또는 build_linux.sh 의 입력받은 username이 상이할경우 docker image생성후 docker 이미지 실행시 아래와 같은 에러가 발생합니다.

Error: Invalid user name dockeruser
For help, use /home/%username%/anaconda2/bin/supervisord -h

**Comment by joelkim** [comment]
0abf9c133081502d4db5a9bb99aa2c779851e26f 로 커밋 새로 했습니다.
supervisord.conf 의 user 필드를 제거하고 username이 다를 시에도 돌아가도록 조치하였습니다. 
지적 감사합니다.
