### ISSUE TITLE
build_linux.sh run error

### ISSUE THREAD

**Issue by sifnoc** [datascienceschool/docker_rpython#2]
빌드시 에러가 납니다.

>ubuntu@ubuntu:~/Downloads/docker_rpython$ sudo sh build_linux.sh
tag (default "latest"):
user name (default "dockeruser"):
user uid (default 1999 or current uid 0):
user gid (default 1999 or current uid 0):
build_linux.sh: 33: read: Illegal option -t
-e
Input timed out
Looks like something went wrong... Press any key to continue...build_linux.sh: 1: read: arg count

build_linux.sh 해당 부분 수정시 정상 작동 합니다.
>#if read -t 5 -sp "user password: " USER_PASS; then
  if read -p "user password: " USER_PASS; then
  echo
  if [ -z "$USER_PASS" ]; then
    USER_PASS=$DEFAULT_USER_PASS
  fi
  #if read -t 5 -sp "password (again): " USER_PASS2; then
  if read -p "password (again): " USER_PASS2; then
    if [ -z "$USER_PASS2" ]; then
      USER_PASS2=$DEFAULT_USER_PASS
    fi
    if [[ $USER_PASS != $USER_PASS2 ]]; then
      echo
      echo "passwords are different" >&2
      exit 1
    fi
    echo
  else
    echo -e "\nInput timed out" >&2
  exit 1
  fi
else
  echo -e "\nInput timed out" >&2
  exit 1
fi

**Comment by joelkim** [comment]
-t 옵션을 제거하였습니다.
https://github.com/datascienceschool/docker_rpython/commit/5e6901374c957605f0abb742c9698cf8a4566a1e
